---
title: "Richness and Yield Supplemental Figures"
output: html_document
date: "2025-04-24"
---

```{r}
df <- read.csv('../../2412_normalizedabundancetable_rarefied_singremoved.csv')
dfa <- df %>% select(X:AC4_2)  %>% column_to_rownames(var = 'X') %>% filter(rowSums(across(where(is.numeric)))!=0) %>% filter(rowSums(. > 0) > 1)
dfh <- df %>% select(X, HA10_1:HC4_2)  %>% column_to_rownames(var = 'X') %>%  filter(rowSums(across(where(is.numeric)))!=0) %>% filter(rowSums(. > 0) > 1)

meta <- read.csv('../../2412_metadataALL.csv') %>% mutate(month_date = case_when(Timepoint == "10" ~ "11/14",
                                                                              Timepoint == "1" ~ "3/19",
                                                                              Timepoint == "2" ~"4/7",
                                                                              Timepoint == "3" ~'4/29', 
                                                                              Timepoint == "4" ~ '5/21', 
                                                                              Timepoint == "6" ~'6/15'))
metaa <- meta %>% filter(Site == 'Angelo')
metah <- meta %>% filter(Site == 'Hopland')

dfa <- dfa[, match(metaa$SampleID, colnames(dfa))]
dfh <- dfh[, match(metah$SampleID, colnames(dfh))]
```

```{r}
otua <- t(dfa %>% mutate_if(is.numeric, round))
richness <- estimateR(otua)
evenness <- diversity(otua) / log(specnumber(otua))
shannon <- diversity(otua, index = "shannon")
simpson <- diversity(otua, "simpson")
ang_alphadiv <- as.data.frame(cbind(metaa, t(richness), 
                         shannon, evenness, simpson))  %>% remove_rownames()
otuh <- t(dfh %>% mutate_if(is.numeric, round))
richness <- estimateR(otuh)
evenness <- diversity(otuh) / log(specnumber(otuh))
shannon <- diversity(otuh, index = "shannon")
simpson <- diversity(otuh, "simpson")
hop_alphadiv <- as.data.frame(cbind(metah, t(richness), 
                         shannon, evenness, simpson)) %>% remove_rownames()

alphadiv <- rbind(ang_alphadiv, hop_alphadiv) %>% mutate(month_day = paste0(month(date_collected), "/", day(date_collected)))

#stats are in script for figure 3 which is how I got the annotations below

sig_annotations_rep <- data.frame(
  Site = c(rep("Angelo", 2)),
  xminbar = c("A", "B"),
  xmaxbar = c("B", "C"),
  xposstar = c(1.5, 2.5),
  y.position.bar = c(2500, 2400),
  label = c("**", "**")
)

#plotting by rep for supplementary
(alphaplotsrep <- ggplot(alphadiv, aes(x=Rep, y=S.obs)) +
  geom_boxplot(aes(fill=Rep), col = 'black', show.legend = FALSE) + #shape = Rep
  labs(x= 'Sampling Zone', y= 'Viral Richness') +
    theme_transparent()+
   facet_wrap(~Site)  +
    geom_segment(data = sig_annotations_rep,
               aes(x = xminbar, xend = xmaxbar, y = y.position.bar, yend = y.position.bar),
               inherit.aes = FALSE, linewidth = 0.6) +
    geom_text(data = sig_annotations_rep,
            aes(x = xposstar, y = y.position.bar + 30, label = label),
            inherit.aes = FALSE, size = 4) +
    theme(
    legend.text = element_text(size = 8),
    legend.title = element_text(size = 8, face="bold"),
    legend.position = "bottom",
    axis.text.x = element_text(size = 8),
    axis.text.y = element_text(size = 8),
    plot.title = element_text(size = 10, face="bold"),
    axis.title.x = element_text(size = 9, face="bold"),
    axis.title.y = element_text(size = 9, face="bold"),
    strip.text.x = element_text(size = 10, face = "bold")
    ))
```

```{r}
df <- read.csv('../../../2203_wateryear_yeilds.csv')
df$Site <- sapply(strsplit(df$Sample, '_'), `[`, 1)
df$Rep <- sapply(strsplit(df$Sample, '_'), `[`, 2)
df$Time <- sapply(strsplit(df$Sample, '_'), `[`, 3)
df$SubRep <- sapply(strsplit(df$Sample, '_'), `[`, 4)
df$Site <- ifelse(df$Site == 'H', 'Hopland', ifelse(df$Site == 'A', 'Angelo', df$Site))
df$Total_DNA <- df$DNA.Yeild * 98
dffilt <- df %>% filter(Time %in% c("1", "2", "3", "4", "6", "10"))
dffilt2 <- dffilt %>% mutate(SampleName = paste(substr(Site, 1,1), Rep, Time, "_", SubRep, sep = ""))
```


```{r}
dataforcorr <- left_join(dffilt2, alphadiv, by = c("SampleName" = "SampleID"))

(plotyr <- ggplot(dataforcorr, aes(x = S.obs, y = Total_DNA)) + geom_point() + facet_wrap(~Site.x, scales = "free")  + geom_smooth(method = lm) + 
  stat_regline_equation(aes(label = ..eq.label..), formula = y ~ x) +
  stat_cor(aes(label = paste(..rr.label.., ..p.label.., sep = "*`,`~")), label.y.npc = 0.92, size = 3) + labs(x = "Richness", y = "Total DNA (ng)"))
```

```{r}
(ayplot <- plot_grid(alphaplotsrep, plotyr, ncol = 1, labels = c("A", "B")) + theme(plot.background = element_rect(fill = "white", color = 'white')))

ggsave("RichnessbyRep_Richnessyieldcorrelation.png", ayplot, height = 7, width = 7)
```

